# Do not edit. Generated by the configure script.
export PATH:=/mnt/c/Users/kakunge/Downloads/node-v18.18.0/out/tools/bin:$(PATH)
BUILDTYPE=Release
NODE_TARGET_TYPE=executable
PYTHON=/usr/bin/python3.9
PREFIX=/usr/local
